### ISSUE TITLE
请问browser path填写的是哪个

### ISSUE THREAD

**Issue by Yubo0311** [thezzisu/pku-elective#2]

**Comment by thezzisu** [comment]
如果你是Windows，可以直接填写edge的路径 `C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe`

否则填写chrome浏览器的路径

**Comment by Yubo0311** [comment]
谢谢！那对于macOS就是chrome的路径是吗（Safari可以吗）

**Comment by thezzisu** [comment]
必须是chromium系列的浏览器（见puppeteer文档）
