### ISSUE TITLE
Wait for captcha input?

### ISSUE THREAD

**Issue by msuwakow** [thezzisu/pku-elective#3]
I attempted to deploy this repo, then after started, I got requests for the captcha like this:

![pic_0](https://github.com/thezzisu/pku-elective/assets/55381285/6fb29129-4d0b-4b3a-ba4f-07f50960e4d9)

Now the elective is not available, but one could imply that captcha will be requested after the elective admission.

What should I do to solve the captcha? Do I need to import extra libs like [this](https://github.com/zhongxinghong/PKUElectiveCaptcha)? If so, what's the best way to do it?

**Comment by msuwakow** [comment]
By the way, the blank for captcha is not capable for the direct keyboard input: It will "Start!!!" after the first letter or digit was input.

**Comment by thezzisu** [comment]
You need to manually input captcha right after started election.
The captcha is valid within one browser session, and will only expire after one action (in this project, only election is supported).
The input problem is related to IME. Please use "English Keyboard" as IME and retry.
